### ISSUE TITLE
Live preview quality

### ISSUE THREAD

**Issue by araujokth** [miralabs/mira-unity-sdk#14]
Hi,

When running in live preview the content appearing on the iphone looks quite pixelized. I was wondering if that is normal even if one follows the quality level instructions explained here https://developer.mirareality.com/docs/mira-live-preview or did I set something wrong?

**Comment by cbarronmira** [comment]
Hi @araujokth, the jpeg quality can be adjusted in the editor, on the live preview video component:
![image](https://user-images.githubusercontent.com/31075468/38825801-abda3728-4162-11e8-8b32-716d95cc4b3c.png)

However, keep in mind that the live preview app is streaming the screen from the editor to the phone (either wirelessly or over usb), and so increasing the quality of the image can result in lag due to frames accumulating when the phone cannot process them quickly enough

**Comment by cbarronmira** [comment]
Also, you do not need to rebuild the app to make this change, it is only on the editor side

**Comment by araujokth** [comment]
Thanks a lot! I will keep that in mind
